import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import Box from '@mui/material/Box'
import CssBaseline from '@mui/material/CssBaseline'
import { ThemeProvider } from '@mui/material/styles'
import type { Metadata } from 'next'

import AppSidebar from '@/app/components/AppSidebar'
import theme from './theme' // is error in docs on https://mui.com/material-ui/integrations/nextjs/?

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'My Material UI Flickr Feed',
  description: 'Generated by create next app',
}
const drawerWidth = 240
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />

            <AppSidebar drawerWidth={drawerWidth} />
            <Box
              component="main"
              sx={{
                flexGrow: 1,
                bgcolor: 'background.default',
                p: 3,
                ml: `${drawerWidth}px`,
              }}
            >
              {children}
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
